model_name: QuadrotorPointload
gravity: 9.81
massQ: 0.533
massL: 0.075
mass: 0.608
cable_length: 0.52 #0.507 #0.301
distance_tag_CoG: 0.026
Ixx: 2.64e-3
Iyy: 2.64e-3
Izz: 4.96e-3
thrust_coefficient: 5.55e-8
prop_radius: 0.099
arm_length: 0.17
motor_time_constant: 0.05
min_rpm: 1500
max_rpm: 7500
drag_coefficient: 0.0
