gains:
  pos: {x: 8.5, y: 8.5, z: 18.0}
  vel: {x: 3.2, y: 3.2, z: 3.2}
  ki: {x: 0.02, y: 0.02, z: 0.02}
  rot: {x: 1.2, y: 1.2, z: 0.3}
  ang: {x: 0.15, y: 0.15, z: 0.03}

# high attitude gains
#  pos: {x: 7.0, y: 7.0, z: 15.0}
#  vel: {x: 2.8, y: 2.8, z: 3.0}
#  ki: {x: 0.02, y: 0.02, z: 0.02}
#  rot: {x: 1.8, y: 1.8, z: 0.3}
#  ang: {x: 0.18, y: 0.18, z: 0.03}

gainsL:
  pos: {x: 0.0, y: 0.0, z: 10.0}
  vel: {x: 0.0, y: 0.0, z: 8.0}
  p: 0.1
  vp: 0.0

 # pos: {x: 0.5, y: 0.5, z: 10.0}
 # vel: {x: 0.8, y: 0.8, z: 10.0}
 # p: 4.0
#  vp: 1.0
  rot: {x: 1.2, y: 1.2, z: 0.3}
  ang: {x: 0.15, y: 0.15, z: 0.03}

corrections:
  kf: 0.9e-08
#  kf: -1.1e-08
  r: 0.0
  p: 0.0

