##########QUADROTOR
#gains:
 # pos: {x: 8.5, y: 8.5, z: 18.0}
 # vel: {x: 3.2, y: 3.2, z: 3.2}
  #ki: {x: 0.02, y: 0.02, z: 0.02}
 # rot: {x: 1.0, y: 1.0, z: 0.4}
 # ang: {x: 0.05, y: 0.05, z: 0.04} 

#  rot: {x: 1.2, y: 1.2, z: 0.3}
#  ang: {x: 0.15, y: 0.15, z: 0.03}

# Used on odroid quad
#  rot: {x: 1.5, y: 1.5, z: 0.4}
#  ang: {x: 0.1, y: 0.1, z: 0.04}

############# PAYLOAD
# USING THIS ON THE QUADROTOR
#gains:
#  pos: {x: 6.0, y: 6.0, z: 9.3} 
#  vel: {x: 3.5, y: 3.5, z: 5.4} 
#  ki:  {x: 0.00, y: 0.00, z: 0.00}
#  kib: {x: 0.00, y: 0.00, z: 0.00}
#  rot: {x: 1.2, y: 1.2, z: 1.0}
#  ang: {x: 0.10, y: 0.10, z: 0.10}


# high attitude gains
#  pos: {x: 7.0, y: 7.0, z: 15.0}
#  vel: {x: 2.8, y: 2.8, z: 3.0}
#  ki: {x: 0.02, y: 0.02, z: 0.02}
#  rot: {x: 1.8, y: 1.8, z: 0.3}
#  ang: {x: 0.18, y: 0.18, z: 0.03}


# actual robot, no feedforward
#gainsL:
#  pos: {x: 2.0, y: 2.0, z: 15.0}
#  vel: {x: 1.5, y: 1.5, z: 8.0}
#  p: 5.0
#  vp: 8.0
  

# actual robot, feedforward - barely stable
#gainsL:
#  pos: {x: 2.0, y: 2.0, z: 15.0}
#  vel: {x: 1.5, y: 1.5, z: 8.0}
#  p: 5.0
#  vp: 8.0

#gainsL:
#  pos: {x: 3.0, y: 3.0, z: 13.0} #12.0
#  vel: {x: 2.1, y: 2.1, z: 8.0}  #8.0
#  p: 8.0
#  vp: 6.0

#  rot: {x: 1.0, y: 1.0, z: 0.4}
#  ang: {x: 0.05, y: 0.05, z: 0.04}
  
########## SIMULATOR

gains:
  pos: {x: 7.4, y: 7.4, z: 10.4}
  vel: {x: 4.8, y: 4.8, z: 6.0}
  ki:  {x: 0.00, y: 0.00, z: 0.00}
  kib: {x: 0.00, y: 0.00, z: 0.00}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}


# simulator w/feedforward
#gainsL:
#  pos: {x: 0.5, y: 0.5, z: 30.0} #0.5 # 0.7
#  vel: {x: 1.8, y: 1.8, z: 20.0} #2.0 #1.3
#  p: 12.0 # 12
#  vp: 6.0 #6

# simulator, with f_n = A dot p (current)
#gainsL:
#  pos: {x: 0.7, y: 0.7, z: 30.0}
#  vel: {x: 1.3, y: 1.3, z: 16.0}
#  p: 30.0
#  vp: 16.0

# simulator, no feedforward
#gainsL:
#  pos: {x: 0.7, y: 0.7, z: 30.0}
#  vel: {x: 1.3, y: 1.3, z: 16.0}
#  p: 30.0
#  vp: 16.0

#  rot: {x: 1.5, y: 1.5, z: 1.0}
#  ang: {x: 0.13, y: 0.13, z: 0.1}


# simulator
#gainsL:
#  pos: {x: 0.7, y: 0.7, z: 30.0}
#  vel: {x: 1.3, y: 1.3, z: 8.0}
#  p: 30.0
#  vp: 16.0

# no feedforward
gainsL:
  pos: {x: 0.7, y: 0.7, z: 30.0}
  vel: {x: 1.3, y: 1.3, z: 16.0}
  ki:  {x: 0.02, y: 0.02, z: 0.0}
  p: 30.0
  vp: 16.0

  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}


corrections:
#  kf: 0.59e-08
  kf: 0.9e-08
  r: 0.0
  p: 0.0

max_pos_int: 2.0