gains:
  pos: {x: 8.5, y: 8.5, z: 18.0}
  vel: {x: 3.2, y: 3.2, z: 3.2}
  ki: {x: 0.02, y: 0.02, z: 0.02}
  rot: {x: 1.2, y: 1.2, z: 0.3}
  ang: {x: 0.15, y: 0.15, z: 0.03}

# high attitude gains
#  pos: {x: 7.0, y: 7.0, z: 15.0}
#  vel: {x: 2.8, y: 2.8, z: 3.0}
#  ki: {x: 0.02, y: 0.02, z: 0.02}
#  rot: {x: 1.8, y: 1.8, z: 0.3}
#  ang: {x: 0.18, y: 0.18, z: 0.03}

gainsL:
  pos: {x: 0.7, y: 0.7, z: 30.0}
  vel: {x: 1.3, y: 1.3, z: 8.0}
  p: 30.0
  vp: 16.0

# no feedforward
#gainsL:
#  pos: {x: 0.7, y: 0.7, z: 30.0}
#  vel: {x: 1.3, y: 1.3, z: 16.0}
#  p: 30.0
#  vp: 16.0

  rot: {x: 1.2, y: 1.2, z: 0.3}
  ang: {x: 0.15, y: 0.15, z: 0.03}

corrections:
  kf: 0.9e-08
#  kf: -1.1e-08
  r: 0.0
  p: 0.0

