quadrotor_names: ['Tango','Victor','Happy','Sneezy','Uniform','Xray','Whiskey','Dopey','Grumpy']
sim_init_x: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
sim_init_y: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
sim_init_z: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
usb : [0, 1,2,3,4,5,6,7,8]