gains:
  pos: {x: 7.4, y: 7.4, z: 10.4}
  vel: {x: 4.8, y: 4.8, z: 6.0}
  ki: {x: 0.02, y: 0.02, z: 0.02}
  rot: {x: 0.8, y: 0.8, z: 0.3}
  ang: {x: 0.1, y: 0.1, z: 0.05}

# high attitude gains
#  pos: {x: 7.0, y: 7.0, z: 15.0}
#  vel: {x: 2.8, y: 2.8, z: 3.0}
#  ki: {x: 0.02, y: 0.02, z: 0.02}
#  rot: {x: 1.8, y: 1.8, z: 0.3}
#  ang: {x: 0.18, y: 0.18, z: 0.03}


corrections:
  kf: 0.0 
  #0.9e-08
#  kf: -1.1e-08
  r: 0.0
  p: 0.0

